"""Market timing, sector rotation, and stock screening module.

Purpose:
- Evaluate market timing / risk-on-risk-off condition.
- Rank sectors to identify potential sectors and exit / underweight sectors.
- Rank stocks to identify potential candidates and exit / reduce candidates.

This is decision-support for CRO / Risk Committee, not investment advice.
It reads CSV files under data/raw/ generated by update_market_data.py.
"""
from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd

RAW_DIR = Path("data/raw")


def add_technical_features(df: pd.DataFrame) -> pd.DataFrame:
    data = df.copy()
    if data.empty:
        return data
    data["symbol"] = data["symbol"].astype(str).str.upper().str.strip()
    data["date"] = pd.to_datetime(data["date"], errors="coerce")
    data["close"] = pd.to_numeric(data["close"], errors="coerce")
    data = data.dropna(subset=["date", "close"]).sort_values(["symbol", "date"])

    def calc(g: pd.DataFrame) -> pd.DataFrame:
        g = g.sort_values("date").copy()
        g["ret_1d"] = g["close"].pct_change()
        g["ret_5d"] = g["close"].pct_change(5)
        g["ret_20d"] = g["close"].pct_change(20)
        g["ret_60d"] = g["close"].pct_change(60)
        g["ma_20"] = g["close"].rolling(20, min_periods=10).mean()
        g["ma_50"] = g["close"].rolling(50, min_periods=20).mean()
        g["ma_100"] = g["close"].rolling(100, min_periods=40).mean()
        g["vol_20d"] = g["ret_1d"].rolling(20, min_periods=10).std() * np.sqrt(252)
        g["peak_60d"] = g["close"].rolling(60, min_periods=20).max()
        g["drawdown_60d"] = g["close"] / g["peak_60d"] - 1

        delta = g["close"].diff()
        gain = delta.clip(lower=0).rolling(14, min_periods=7).mean()
        loss = (-delta.clip(upper=0)).rolling(14, min_periods=7).mean()
        rs = gain / loss.replace(0, np.nan)
        g["rsi_14"] = 100 - (100 / (1 + rs))
        return g

    return data.groupby("symbol", group_keys=False).apply(calc)


def latest_by_symbol(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    data = add_technical_features(df)
    return data.sort_values("date").groupby("symbol", as_index=False).tail(1)


def market_timing_signal(market_df: pd.DataFrame) -> dict:
    latest = latest_by_symbol(market_df)
    if latest.empty:
        return {"signal": "No data", "score": 0, "action": "No action", "reason": "No market data."}

    row = latest.iloc[-1]
    score = 0
    reasons = []

    if row.get("close", np.nan) > row.get("ma_20", np.nan):
        score += 1; reasons.append("Close > MA20")
    else:
        score -= 1; reasons.append("Close < MA20")

    if row.get("ma_20", np.nan) > row.get("ma_50", np.nan):
        score += 1; reasons.append("MA20 > MA50")
    else:
        score -= 1; reasons.append("MA20 < MA50")

    if row.get("ret_20d", 0) > 0:
        score += 1; reasons.append("20D return positive")
    else:
        score -= 1; reasons.append("20D return negative")

    if row.get("drawdown_60d", 0) > -0.07:
        score += 1; reasons.append("Drawdown controlled")
    else:
        score -= 1; reasons.append("Drawdown > 7%")

    if row.get("vol_20d", 0) < 0.25:
        score += 1; reasons.append("Volatility acceptable")
    else:
        score -= 1; reasons.append("Volatility high")

    if score >= 3:
        signal = "Risk-on / Can enter selectively"
        action = "Can increase exposure selectively; prioritize strong sectors and high-quality stocks."
    elif score <= -3:
        signal = "Risk-off / Reduce exposure"
        action = "Reduce beta, cut weak sectors/stocks, raise cash."
    else:
        signal = "Neutral / Wait"
        action = "Keep moderate exposure; wait for trend confirmation."

    return {"signal": signal, "score": int(score), "action": action, "reason": "; ".join(reasons)}


def load_price_universe(raw_dir: Path = RAW_DIR) -> pd.DataFrame:
    frames = []
    for path in sorted(raw_dir.glob("market_*.csv")):
        try:
            df = pd.read_csv(path)
            if "symbol" not in df.columns:
                df["symbol"] = path.stem.replace("market_", "").upper()
            frames.append(df)
        except Exception:
            continue
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_sector_map(raw_dir: Path = RAW_DIR) -> pd.DataFrame:
    path = raw_dir / "sector_map.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    df.columns = [str(c).strip().lower() for c in df.columns]
    if "ticker" in df.columns and "symbol" not in df.columns:
        df = df.rename(columns={"ticker": "symbol"})
    if "symbol" in df.columns:
        df["symbol"] = df["symbol"].astype(str).str.upper().str.strip()
    return df


def rank_stocks(price_df: pd.DataFrame, sector_map: pd.DataFrame | None = None) -> pd.DataFrame:
    data = price_df.copy()
    if data.empty:
        return pd.DataFrame()

    if "symbol" not in data.columns:
        return pd.DataFrame()

    data["symbol"] = data["symbol"].astype(str).str.upper().str.strip()

    if "sector" not in data.columns and sector_map is not None and not sector_map.empty:
        data = data.merge(sector_map[["symbol", "sector"]], on="symbol", how="left")

    latest = latest_by_symbol(data)
    if latest.empty:
        return pd.DataFrame()

    latest["above_ma20"] = (latest["close"] > latest["ma_20"]).astype(int)
    latest["above_ma50"] = (latest["close"] > latest["ma_50"]).astype(int)

    latest["score"] = (
        latest["ret_20d"].rank(pct=True)
        + latest["ret_60d"].rank(pct=True)
        + latest["above_ma20"]
        + latest["above_ma50"]
        - latest["vol_20d"].rank(pct=True) * 0.5
        + latest["drawdown_60d"].rank(pct=True)
    )

    q75 = latest["score"].quantile(0.75)
    q25 = latest["score"].quantile(0.25)

    def rec(x: float) -> str:
        if x >= q75:
            return "Potential candidate"
        if x <= q25:
            return "Exit / Reduce candidate"
        return "Neutral"

    latest["recommendation"] = latest["score"].apply(rec)

    cols = [
        "symbol", "sector", "date", "close", "ret_5d", "ret_20d", "ret_60d",
        "vol_20d", "drawdown_60d", "rsi_14", "score", "recommendation",
    ]
    cols = [c for c in cols if c in latest.columns]
    return latest[cols].sort_values("score", ascending=False)


def rank_sectors(price_df: pd.DataFrame, sector_map: pd.DataFrame | None = None) -> pd.DataFrame:
    stocks = rank_stocks(price_df, sector_map)
    if stocks.empty or "sector" not in stocks.columns:
        return pd.DataFrame()

    sector = stocks.dropna(subset=["sector"]).groupby("sector", as_index=False).agg(
        n_stocks=("symbol", "count"),
        avg_score=("score", "mean"),
        avg_ret_20d=("ret_20d", "mean"),
        avg_ret_60d=("ret_60d", "mean"),
        avg_vol_20d=("vol_20d", "mean"),
        avg_drawdown_60d=("drawdown_60d", "mean"),
    )

    if sector.empty:
        return sector

    q70 = sector["avg_score"].quantile(0.70)
    q30 = sector["avg_score"].quantile(0.30)

    def rec(x: float) -> str:
        if x >= q70:
            return "Potential / Overweight"
        if x <= q30:
            return "Exit / Underweight"
        return "Neutral / Hold"

    sector["recommendation"] = sector["avg_score"].apply(rec)
    return sector.sort_values("avg_score", ascending=False)


def build_market_analysis(market_df: pd.DataFrame, raw_dir: Path = RAW_DIR) -> dict:
    universe = load_price_universe(raw_dir)
    sector_map = load_sector_map(raw_dir)

    if universe.empty:
        universe = market_df.copy()

    return {
        "timing": market_timing_signal(market_df),
        "sector_rank": rank_sectors(universe, sector_map),
        "stock_rank": rank_stocks(universe, sector_map),
        "universe": universe,
    }
